// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        (unknown)
// source: proto/kinsyn.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_kinsyn_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kinsyn_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_kinsyn_proto_rawDescGZIP(), []int{0}
}

type Highlight struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	BookTitle         string `protobuf:"bytes,2,opt,name=book_title,json=bookTitle,proto3" json:"book_title,omitempty"`
	BookAuthor        string `protobuf:"bytes,3,opt,name=book_author,json=bookAuthor,proto3" json:"book_author,omitempty"`
	BookLocationStart int32  `protobuf:"varint,4,opt,name=book_location_start,json=bookLocationStart,proto3" json:"book_location_start,omitempty"`
	BookLocationEnd   int32  `protobuf:"varint,5,opt,name=book_location_end,json=bookLocationEnd,proto3" json:"book_location_end,omitempty"`
	CreatedAt         string `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Content           string `protobuf:"bytes,7,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *Highlight) Reset() {
	*x = Highlight{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_kinsyn_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Highlight) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Highlight) ProtoMessage() {}

func (x *Highlight) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kinsyn_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Highlight.ProtoReflect.Descriptor instead.
func (*Highlight) Descriptor() ([]byte, []int) {
	return file_proto_kinsyn_proto_rawDescGZIP(), []int{1}
}

func (x *Highlight) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Highlight) GetBookTitle() string {
	if x != nil {
		return x.BookTitle
	}
	return ""
}

func (x *Highlight) GetBookAuthor() string {
	if x != nil {
		return x.BookAuthor
	}
	return ""
}

func (x *Highlight) GetBookLocationStart() int32 {
	if x != nil {
		return x.BookLocationStart
	}
	return 0
}

func (x *Highlight) GetBookLocationEnd() int32 {
	if x != nil {
		return x.BookLocationEnd
	}
	return 0
}

func (x *Highlight) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Highlight) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type HighlightList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Highlights []*Highlight `protobuf:"bytes,1,rep,name=highlights,proto3" json:"highlights,omitempty"`
}

func (x *HighlightList) Reset() {
	*x = HighlightList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_kinsyn_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HighlightList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HighlightList) ProtoMessage() {}

func (x *HighlightList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kinsyn_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HighlightList.ProtoReflect.Descriptor instead.
func (*HighlightList) Descriptor() ([]byte, []int) {
	return file_proto_kinsyn_proto_rawDescGZIP(), []int{2}
}

func (x *HighlightList) GetHighlights() []*Highlight {
	if x != nil {
		return x.Highlights
	}
	return nil
}

var File_proto_kinsyn_proto protoreflect.FileDescriptor

var file_proto_kinsyn_proto_rawDesc = []byte{
	0x0a, 0x12, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6b, 0x69, 0x6e, 0x73, 0x79, 0x6e, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x07, 0x0a, 0x05, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x22, 0xf0, 0x01, 0x0a, 0x09, 0x48, 0x69, 0x67, 0x68, 0x6c, 0x69, 0x67,
	0x68, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x62, 0x6f, 0x6f, 0x6b, 0x5f, 0x74, 0x69, 0x74, 0x6c, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x62, 0x6f, 0x6f, 0x6b, 0x54, 0x69, 0x74, 0x6c,
	0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x62, 0x6f, 0x6f, 0x6b, 0x5f, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x62, 0x6f, 0x6f, 0x6b, 0x41, 0x75, 0x74, 0x68,
	0x6f, 0x72, 0x12, 0x2e, 0x0a, 0x13, 0x62, 0x6f, 0x6f, 0x6b, 0x5f, 0x6c, 0x6f, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x5f, 0x73, 0x74, 0x61, 0x72, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x11, 0x62, 0x6f, 0x6f, 0x6b, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61,
	0x72, 0x74, 0x12, 0x2a, 0x0a, 0x11, 0x62, 0x6f, 0x6f, 0x6b, 0x5f, 0x6c, 0x6f, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x5f, 0x65, 0x6e, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0f, 0x62,
	0x6f, 0x6f, 0x6b, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x45, 0x6e, 0x64, 0x12, 0x1d,
	0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x18, 0x0a,
	0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0x41, 0x0a, 0x0d, 0x48, 0x69, 0x67, 0x68, 0x6c,
	0x69, 0x67, 0x68, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x30, 0x0a, 0x0a, 0x68, 0x69, 0x67, 0x68,
	0x6c, 0x69, 0x67, 0x68, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x48, 0x69, 0x67, 0x68, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x52, 0x0a,
	0x68, 0x69, 0x67, 0x68, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x73, 0x32, 0x43, 0x0a, 0x0b, 0x49, 0x6e,
	0x70, 0x75, 0x74, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x12, 0x34, 0x0a, 0x0e, 0x53, 0x79, 0x6e,
	0x63, 0x48, 0x69, 0x67, 0x68, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x73, 0x12, 0x0c, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x48, 0x69, 0x67, 0x68, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x32,
	0x46, 0x0a, 0x0c, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x12,
	0x36, 0x0a, 0x10, 0x53, 0x65, 0x6e, 0x64, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x48, 0x69, 0x67, 0x68,
	0x6c, 0x69, 0x67, 0x68, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x1a, 0x0c, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_kinsyn_proto_rawDescOnce sync.Once
	file_proto_kinsyn_proto_rawDescData = file_proto_kinsyn_proto_rawDesc
)

func file_proto_kinsyn_proto_rawDescGZIP() []byte {
	file_proto_kinsyn_proto_rawDescOnce.Do(func() {
		file_proto_kinsyn_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_kinsyn_proto_rawDescData)
	})
	return file_proto_kinsyn_proto_rawDescData
}

var file_proto_kinsyn_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_kinsyn_proto_goTypes = []any{
	(*Empty)(nil),         // 0: proto.Empty
	(*Highlight)(nil),     // 1: proto.Highlight
	(*HighlightList)(nil), // 2: proto.HighlightList
}
var file_proto_kinsyn_proto_depIdxs = []int32{
	1, // 0: proto.HighlightList.highlights:type_name -> proto.Highlight
	0, // 1: proto.InputPlugin.SyncHighlights:input_type -> proto.Empty
	2, // 2: proto.OutputPlugin.SendNotification:input_type -> proto.HighlightList
	2, // 3: proto.InputPlugin.SyncHighlights:output_type -> proto.HighlightList
	0, // 4: proto.OutputPlugin.SendNotification:output_type -> proto.Empty
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_kinsyn_proto_init() }
func file_proto_kinsyn_proto_init() {
	if File_proto_kinsyn_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_kinsyn_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_kinsyn_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*Highlight); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_kinsyn_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*HighlightList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_kinsyn_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_kinsyn_proto_goTypes,
		DependencyIndexes: file_proto_kinsyn_proto_depIdxs,
		MessageInfos:      file_proto_kinsyn_proto_msgTypes,
	}.Build()
	File_proto_kinsyn_proto = out.File
	file_proto_kinsyn_proto_rawDesc = nil
	file_proto_kinsyn_proto_goTypes = nil
	file_proto_kinsyn_proto_depIdxs = nil
}
